AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: MLDA Hackathon 2022 - Core Resources

Parameters:

  AppName:
    Type: String
    Description: "Name of Application"
    Default: Good-Vibes

Resources:

  ConnectionDDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Join ["-", [!Ref AppName, "user", "connections"]]
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "connectionId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "connectionId"
          KeyType: "HASH"
      
      